<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1e545d49-72f8-4685-bb64-960eda7320a2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
   
  </ItemGroup>

</Project>
